@API_HostAddress = http://localhost:5283

GET {{API_HostAddress}}/contacts/
Accept: application/json

###

POST {{API_HostAddress}}/contacts/
Accept: application/json

###

PUT {{API_HostAddress}}/contacts/{id}
Accept: application/json

###

DELETE {{API_HostAddress}}/contacts/{id}
Accept: application/json

###

GET {{API_HostAddress}}/meetings/
Accept: application/json

###

POST {{API_HostAddress}}/meetings/
Accept: application/json
