// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Domain.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsInterviewSchedule")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5eb949eb-58cb-48bc-b978-df33e9942c61"),
                            Email = "alice.johnson@techcorp.com",
                            IsInterviewSchedule = true,
                            Name = "Alice Johnson",
                            OrganizationName = "TechCorp",
                            Phone = "123-456-7890"
                        },
                        new
                        {
                            Id = new Guid("f3751eb7-3533-4911-bfef-c8ea4254e5b8"),
                            Email = "bob.smith@innovatex.com",
                            IsInterviewSchedule = false,
                            Name = "Bob Smith",
                            OrganizationName = "InnovateX",
                            Phone = "234-567-8901"
                        });
                });

            modelBuilder.Entity("API.Models.Domain.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("InterviewDateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsRemote")
                        .HasColumnType("bit");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POCPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PrimaryContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("RateHourlyOrSalary")
                        .HasColumnType("float");

                    b.Property<int?>("Round")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContactId")
                        .IsUnique()
                        .HasFilter("[ContactId] IS NOT NULL");

                    b.HasIndex("PrimaryContactId");

                    b.ToTable("Meetings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("edbd9e35-be09-4446-9cb6-8c3b4fcb6fdc"),
                            ContactId = new Guid("5eb949eb-58cb-48bc-b978-df33e9942c61"),
                            InterviewDateAndTime = new DateTime(2024, 12, 3, 6, 49, 25, 80, DateTimeKind.Local).AddTicks(6711),
                            IsRemote = true,
                            OrganizationName = "TechCorp",
                            POCPhone = "123-456-7890",
                            PaymentType = "Salary",
                            Position = "Software Engineer",
                            RateHourlyOrSalary = 120000.0,
                            Round = 1
                        },
                        new
                        {
                            Id = new Guid("bf02e668-cdb5-409d-abc9-cc379db08df2"),
                            InterviewDateAndTime = new DateTime(2024, 12, 4, 6, 49, 25, 82, DateTimeKind.Local).AddTicks(2062),
                            IsRemote = false,
                            OrganizationName = "InnovateX",
                            POCPhone = "234-567-8901",
                            PaymentType = "Hourly",
                            Position = "Frontend Developer",
                            PrimaryContactId = new Guid("f3751eb7-3533-4911-bfef-c8ea4254e5b8"),
                            RateHourlyOrSalary = 50.0,
                            Round = 1
                        });
                });

            modelBuilder.Entity("API.Models.Domain.Meeting", b =>
                {
                    b.HasOne("API.Models.Domain.Contact", "Contact")
                        .WithOne("Meeting")
                        .HasForeignKey("API.Models.Domain.Meeting", "ContactId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("API.Models.Domain.Contact", "PrimaryContact")
                        .WithMany("Meetings")
                        .HasForeignKey("PrimaryContactId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Contact");

                    b.Navigation("PrimaryContact");
                });

            modelBuilder.Entity("API.Models.Domain.Contact", b =>
                {
                    b.Navigation("Meeting");

                    b.Navigation("Meetings");
                });
#pragma warning restore 612, 618
        }
    }
}
